{% set name = "ccsds_ndm" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15ad98845d85e6d4135a0ae2e5c4b62ff6cfb65b0e2ff2fa1fd1eb08dab38c08

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - python >={{ python_min }}
    - lxml >=6.0
    - lxml-stubs >=0.5
    - xsdata >=26

test:
  imports:
    - ccsds_ndm
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/egemenimre/ccsds-ndm/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: 'CCSDS-NDM: CCSDS Navigation Data Messages (NDM) Read/Write Library'
  doc_url: https://ccsds-ndm.readthedocs.io/
  dev_url: https://github.com/egemenimre/ccsds-ndm/

  description: CCSDS-NDM is an open source Python package to provide read and write functionality for CCSDS Navigation Data Message (NDM) XML files through an auto-generated object tree. These NDM files carry common data types such as trajectory, orbit, attitude and conjunction events. These data types are routinely 
    generated and exchanged within and between spacecraft operators, space agencies, researchers, amateurs and commercial companies - which are the natural audience for this library.

extra:
  recipe-maintainers:
    - egemenimre
